### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by saksham7778** [filipefborba/HandRecognition#3]
Can you please tell your keras and tensorflow version because there is an error regarding it or please help me to rectify this error 
when i used->
model = keras.models.load_model('handrecognition_model.h5')
following error came->
File "C:\Users\Lenovo\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 251, in load_model
 training_config['weighted_metrics'])
KeyError: 'weighted_metrics'

**Comment by saksham7778** [comment]
aslo when i am training the same model on colab why i am getting accuracy only 10% any idea about it . please reply

**Comment by filipefborba** [comment]
Hey @saksham7778! First, I don't remember the version of my Keras and Tensorflow because I used Colab, so the dependencies were automatically "installed".
Also, I don't know why you're getting 10% accuracy, did you use the Kaggle database and uploaded it all? Keep in mind that this is a very introductory Machine Learning project, so I was still learning when doing it. I recommend you do your own share of research on top of this.

Check this repo out! https://github.com/ageron/handson-ml2

**Comment by saksham7778** [comment]
thanks for replying @filipefborba  . Can u then suggest me any other github repo for this particular project only

**Comment by filipefborba** [comment]
This is the best one I know

**Comment by saksham7778** [comment]
thanks
